site:
  name: Neighbour
  leyend: Technology 
  site: 'https://neighbour.cl'
  base: '/'
  trailingSlash: false
  googleSiteVerificationId: 'nAV4Y6iBI_zv2OgyOJ6x_60rfZ_165YNpE1EfwEQS2E'

# Default SEO metadata
metadata:
  title:
    default: Neighbour
    template: '%s — Technology'
  description: "Innovación y soluciones tecnológicas avanzadas para transformar y optimizar tu negocio. Ofrecemos servicios personalizados en desarrollo web, software y tecnología para llevar tu empresa al siguiente nivel. Descubre cómo nuestras herramientas pueden marcar la diferencia en tu crecimiento empresarial. Contáctanos ahora y da el siguiente paso hacia la digitalización."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Neighbour
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@onwidget'
    site: '@onwidget'
    cardType: summary_large_image

i18n:
  language: es
  textDirection: ltr

analytics:
  vendors:
    googleAnalytics:
      id: "G-VPVW6GJQRS" # or "G-XXXXXXXXXX"

ui:
  theme: 'dark' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"

apps:
  examples:
    - name: Aplicación 1
      description: Ejemplo de descripción de la aplicación 1.
    - name: Aplicación 2
      description: Ejemplo de descripción de la aplicación 2.
